base: 'https://www.kindundhund.ch'
baseVariants:
  -
    base: 'https://kindundhund.ddev.site'
    condition: 'applicationContext == "Development"'
  -
    base: 'https://test.kindundhund.ch'
    condition: 'applicationContext == "Testing"'
dependencies:
  - typo3/seo-sitemap
  - typo3/redirects
  - typo3/felogin
  - typo3/form
  - b13/doktypemapper
  - conpassione/kuhdist
errorHandling:
  -
    errorCode: 404
    errorHandler: Page
    errorContentSource: 't3://page?uid=4'
  -
    errorCode: 500
    errorHandler: Page
    errorContentSource: 't3://page?uid=5'
languages:
  -
    languageId: 0
    title: Deutsch
    navigationTitle: Deutsch
    base: /
    locale: de_CH.UTF-8
    iso-639-1: de
    hreflang: de_CH
    direction: ltr
    flag: ch
    enabled: true
    websiteTitle: 'conPassione | Entwicklungsseite'
rootPageId: 1
routeEnhancers:
  PageTypeSuffix:
    type: PageType
    map:
      sitemap.xml: 1533906435
routes:
  -
    route: robots.txt
    type: staticText
    content: "User-agent: *\r\nDisallow: /typo3/\r\nDisallow: /typo3conf/\r\nSitemap: https://kindundhund.ddev.site/sitemap.xml\r\n"
websiteTitle: 'KIND&HUND'
